CREATE TABLE test(
  id_test INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  nom_test VARCHAR,
  date_execution DATETIME 
)

CREATE TABLE trame(
 id_trame INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 framedate DATETIME,
 MID VARCHAR,
 bench_3 INT,
 bench_5 VARCHAR,
 framesize INT,
 mac_dest VARCHAR,
 mac_src VARCHAR,
 field_1 VARCHAR,
 field_2 INT,
 field_3 INT,
 field_4 INT,
 field_5 INT,
 field_6 INT,
 field_7 INT,
 src_ip VARCHAR,
 dest_ip VARCHAR,
 field_14 VARCHAR,
 field_16 INT,
 field_17 VARCHAR,
 field_18 VARCHAR,
 field_20 INT,
 field_21 INT,
 field_23 VARCHAR,
 field_25 VARCHAR,
 field_26 INT,
 field_28 VARCHAR,
 field_29 VARCHAR,
 field_30 INT,
 field_32 VARCHAR,
 packet_date DATETIME,
 mac_sender VARCHAR,
 sender_ip VARCHAR,
 mac_target VARCHAR,
 target_ip VARCHAR,
 num_test FOREIGN KEY REFERENCES test(id_test)
)
